name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/texutils
    permissions:
      id-token: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base

      - name: Install project
        run: poetry install --no-interaction

      - name: Test project
        run: poetry run pytest

      - name: Test build
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

#      - name: Bump version
#        run: poetry version minor

